# **What it does**: Build, Synce static content Storage Account and Pure CDN endpoint.
# **Why we have it**: Replace manual deployment.
# **Who does it impact**: Frontend App. Domains: https://dev.rafft.jp, https://stg.rafft.jp, https://rafft.jp

name: Frontend - CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - feature.new.ci_cd
    types: [closed]
    paths:
     - '!landingpage/**'

jobs:
  develop:
    if: ( github.ref == 'develop' || github.ref == 'feature.new.ci_cd' ) && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set environment
      run: |
        echo "develop"
        env

  product:
    if: ( github.ref == 'master' || github.ref == 'feature.new.ci_cd' ) && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set environment
      run: |
        echo "master"
        env
